#Global Values
global:
  namespace: default #namespace !! don't touch because have one bug in application ..
  replicaCount: 1
  useSpring: local
  image:
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ports:
    - 80
  service:
    type: ClusterIP
    protocol: TCP
  livenessProbe:
    type: "httpGet"
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    type: "httpGet"
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10

#Value ENV for spring profile
spring:
  local:
    name: SPRING_PROFILES_ACTIVE
    value: local-microservice
  prod:
    name: SPRING_PROFILES_ACTIVE
    value: production-microservice

#Value for deployment configuration
deployments:
  mongodb:
    containers:
      image:
        repository: mongo
        tag: "3.6.23"
      volumeMounts:
        - path: /data/db
          persistentVolumeClaim: true
      probe:
        type: "tcpSocket"
        port: 27017
      readinessProbe: true
      livenessProbe: true
  queue:
    containers:
      image:
        repository: supinfo4kube/queue
        tag: "1.0.1"
      probe:
        port: 8161
      livenessProbe: true

  position-simulator:
    containers:
      image:
        repository: supinfo4kube/position-simulator
        tag: "1.0.1"
      spring: prod

  position-tracker:
    containers:
      image:
        repository: supinfo4kube/position-tracker
        tag: "1.0.1"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      spring: prod

  api-gateway:
    containers:
      image:
        repository: supinfo4kube/api-gateway
        tag: "1.0.1"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "768Mi"
          cpu: "750m"
      spring: prod

  webapp:
    containers:
      image:
        repository: supinfo4kube/web-app
        tag: "1.0.0"
      spring: prod
      probe:
        port: 80
      livenessProbe: true

#Values for service
services:
  mongodb:
    ports:
      - "27017"
  queue:
    type: NodePort
    ports: # if you have two ports target and port the first value is localPort and other is port to
      - "8161:30010" #30010 is NodePort
      - "61616"
  position-tracker:
    ports:
      - "8080"
  api-gateway:
    ports:
      - "8080"
  webapp:
    type: NodePort
    ports:
      - "80:30080"

#Value for persistentVolumes
persistentVolumesClaim:
  mongodb-pv-claim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
