#Global Values
global:
  namespace: default #namespace !! don't touch because have one bug in application ..
  replicaCount: 1
  useSpring: local
  image:
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ports:
    - 80
  service:
    type: ClusterIP
    protocol: TCP
  livenessProbe:
    type: "httpGet"
    path: /
    initialDelaySeconds: 130
    periodSeconds: 60
  readinessProbe:
    type: "httpGet"
    path: /
    initialDelaySeconds: 150
    periodSeconds: 60

#Value ENV for spring profile
spring:
  local:
    name: SPRING_PROFILES_ACTIVE
    value: local-microservice
  prod:
    name: SPRING_PROFILES_ACTIVE
    value: production-microservice

#Value for deployment configuration
deployments:
  mongodb:
    containers:
      image:
        repository: mongo
        tag: "3.6.23"
      volumeMounts:
        - path: /data/db
          persistentVolumeClaim: true
      probe:
        type: "tcpSocket"
        port: 27017
        initialDelaySeconds: 30
      readinessProbe: true
      livenessProbe: true
      ports: 
        - 27017
  queue:
    containers:
      image:
        repository: supinfo4kube/queue
        tag: "1.0.1"
      spring: prod
      probe:
        type: "tcpSocket"
        port: 61616
      livenessProbe: true
      readinessProbe: true
      ports: 
        - 61616
        - 8161

  position-simulator:
    containers:
      image:
        repository: supinfo4kube/position-simulator
        tag: "1.0.1"
      spring: prod

  position-tracker:
    containers:
      image:
        repository: supinfo4kube/position-tracker
        tag: "1.0.1"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      spring: prod
      probe:
        type: "tcpSocket"
        port: 8080
      livenessProbe: true
      readinessProbe: true

  api-gateway:
    containers:
      image:
        repository: supinfo4kube/api-gateway
        tag: "1.0.1"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "768Mi"
          cpu: "750m"
      spring: prod
      probe:
        type: "tcpSocket"
        port: 8080
      livenessProbe: true
      readinessProbe: true

  webapp:
    containers:
      image:
        repository: supinfo4kube/web-app
        tag: "1.0.0"
      spring: prod
      probe:
        port: 80
      livenessProbe: true
      readinessProbe: true

#Values for service
services:
  mongodb:
    ports:
      - "27017"
  queue:
    ports: 
      - "8161" 
      - "61616"
  position-tracker:
    ports:
      - "8080"
  api-gateway:
    ports:
      - "8080"
  webapp:
    type: "LoadBalancer"
    ports:
      - "80"

#Value for persistentVolumes
persistentVolumesClaim:
  mongodb-pv-claim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi

# Default values for vehiculefleet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
