#Global Values
global:
  namespace: default #namespace !! don't touch because have one bug in application ..
  replicaCount: 1
  useSpring: local
  image:
    tag: "latest"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    protocol: TCP
  livenessProbe:
    type: "tcpSocket"
    path: /
    initialDelaySeconds: 130
    periodSeconds: 30
  readinessProbe:
    type: "tcpSocket"
    path: /
    initialDelaySeconds: 150
    periodSeconds: 30

#Value ENV for spring profile
spring:
  local:
    name: SPRING_PROFILES_ACTIVE
    value: local-microservice
  prod:
    name: SPRING_PROFILES_ACTIVE
    value: production-microservice

#Value for deployment configuration
deployments:
  mongodb:
    containers:
      image:
        repository: mongo
        tag: "3.6.23"
      volumeMounts:
        - path: /data/db
          persistentVolumeClaim: true
      probe:
        port: 27017
        initialDelaySeconds: 30
      readinessProbe: true
      livenessProbe: true
  queue:
    containers:
      image:
        repository: supinfo4kube/queue
        tag: "1.0.1"
      spring: prod
      probe:
        port: 61616
      livenessProbe: true
      readinessProbe: true

  position-simulator:
    containers:
      image:
        repository: supinfo4kube/position-simulator
        tag: "1.0.1"
      spring: prod

  position-tracker:
    containers:
      image:
        repository: supinfo4kube/position-tracker
        tag: "1.0.1"
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1000m"
      spring: prod
      probe:
        port: 8080
      livenessProbe: true
      readinessProbe: true

  api-gateway:
    containers:
      image:
        repository: supinfo4kube/api-gateway
        tag: "1.0.1"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "768Mi"
          cpu: "750m"
      spring: prod
      probe:
        port: 8080
      livenessProbe: true
      readinessProbe: true

  webapp:
    containers:
      image:
        repository: supinfo4kube/web-app
        tag: "1.0.0"
      spring: prod
      probe:
        type: "httpGet"
        port: 80
      livenessProbe: true
      readinessProbe: true

#Values for service
services:
  mongodb:
    ports:
      - "27017"
  queue:
    ports:
      - "8161"
      - "61616"
  position-tracker:
    ports:
      - "8080"
  api-gateway:
    ports:
      - "8080"
  webapp:
    type: "LoadBalancer"
    ports:
      - "80"

#Value for persistentVolumes
persistentVolumesClaim:
  mongodb-pv-claim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 3Gi
