#Global Values

global:
  replicaCount: 1
  useSpring: kubernetes
  image:
    tag: "latest"
    pullPolicy: IfNotPresent
  ports:
    - 80
  service:
    type: ClusterIP
    protocol: TCP

spring:
  kubernetes:
    name: SPRING_PROFILES_ACTIVE
    value: kubernetes
  local:
    name: SPRING_PROFILES_ACTIVE
    value: local-microservice
  prod:
    name: SPRING_PROFILES_ACTIVE
    value: production-microservice

#Value for deployment configuration
deployments:
  mongodb:
    containers:
      image:
        repository: mongo
        tag: "3.6.5-jessie"
      ports:
        - 27017
      volumeMounts:
        - path: /data/db
          emptyDir: {}
          persistentVolumeClaim: true

  queue:
    containers:
      image:
        repository: richardchesterwood/k8s-fleetman-queue
        tag: "release2"
      ports:
        - 8161
        - 61616
  simulator:
    containers:
      image:
        repository: richardchesterwood/k8s-fleetman-position-simulator
        tag: "release2"
      spring: prod
  tracker:
    containers:
      image:
        repository: richardchesterwood/k8s-fleetman-position-tracker
        tag: "release3"
      spring: prod
      ports:
        - 8080
  gateway:
    containers:
      image:
        repository: richardchesterwood/k8s-fleetman-api-gateway
        tag: "release2"
      spring: prod
      ports:
        - 8080
        - 30020
  webapp:
    containers:
      image:
        repository: richardchesterwood/k8s-fleetman-webapp-angular
        tag: "release0-5"
      spring: prod
      ports:
        - 80
        - 30080

#Values for service
services:
  mongodb:
    ports:
      - "27017:27017"
  queue:
    ports:
      - "8161:61616"
  simulator:
    ports:
      - "8080"
  tracker:
    ports:
      - "8080"
  gateway:
    ports:
      - "8080:30020"
  webapp:
    type: NodePort
    ports:
      - "8080"

#Value for persistentVolumes
persistentVolumesClaim:
  mongodb-pv-claim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi

# Default values for vehiculefleet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
