
#Boucle sur les valeurs de deployment
{{- range $key, $value := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $value.namespace | default $.Values.global.namespace }}
  name: {{ $key }}
  labels:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}
  {{- end }}
spec:
  replicas: {{ $value.replicaCount | default $.Values.global.replicaCount }}
  selector:
    matchLabels:
      {{- with $value.labels }}
        {{- toYaml . | nindent 6}}
      {{ else }}
        app: {{ $key }}
      {{- end }}
  template:
    metadata:
      labels:
      {{- with $value.labels }}
        {{- toYaml . | nindent 8}}
      {{ else }}
        app: {{ $key }}
      {{- end }}
    spec:
      containers:
        - name: {{ $key }}
          imagePullPolicy: {{ $value.containers.pullPolicy | default $.Values.global.image.pullPolicy }}
          image: "{{ $value.containers.image.repository | default $key }}:{{ $value.containers.image.tag  | default $.Values.global.image.tag}}"
          {{- with $value.containers.resources | default $.Values.global.resources }}
          resources:
            requests:
              memory: {{ .requests.memory }}
              cpu: {{ .requests.cpu }}
            limits:
              memory: {{ .limits.memory }}
              cpu: {{ .limits.cpu }}
          {{- end -}}
          {{- with $value.containers.secret }}
          envFrom :
            - secretRef:
                name: {{ . }}
          {{- end -}}
          {{- if $value.containers.spring }}
          {{- $value := index $.Values.spring $value.containers.spring }}
          env:
            - name: {{ $value.name }}
              value: {{ $value.value }}
          {{- end }}
          {{- if $value.containers.ports}}
          ports:
            {{- range $value.containers.ports | default $.Values.global.ports }}
            - containerPort: {{ . }}
              name: {{ $key }}-{{ . }}
            {{- end }}
          {{- end }}
          {{- if $value.containers.livenessProbe }}
          {{- with $value.containers.probe }}
          livenessProbe:
          {{- $livenessProbeType := .type  | default $.Values.global.livenessProbe.type -}}
          {{- if eq $livenessProbeType "httpGet" }}
            httpGet:
          {{- else if eq $livenessProbeType "tcpSocket"}}
            tcpSocket:
          {{- end }}
          {{- if ne $livenessProbeType "tcpSocket" }}
              path: {{ .path | default $.Values.global.readinessProbe.path}}
          {{- end }}
              port: {{ .port }}
            initialDelaySeconds: {{ .initialDelaySeconds | default $.Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds | default $.Values.global.livenessProbe.periodSeconds }}
          {{- end }}
          {{- end }}
          {{- if $value.containers.readinessProbe }}
          {{- with $value.containers.probe }}
          readinessProbe:
          {{- $readinessProbeType := .type  | default $.Values.global.readinessProbe.type -}}
          {{- if eq $readinessProbeType "httpGet" }}
            httpGet:
          {{- else if eq $readinessProbeType "tcpSocket"}}
            tcpSocket:
          {{- end }}
          {{- if ne $readinessProbeType "tcpSocket" }}
              path: {{ .path | default $.Values.global.readinessProbe.path}}
          {{- end }}
              port: {{ .port }}
            initialDelaySeconds: {{ .initialDelaySeconds | default $.Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds | default $.Values.global.readinessProbe.periodSeconds }}
          {{- end }}
          {{- end }}
    {{- if $value.containers.volumeMounts }}
          volumeMounts:
            {{- range $index, $volume := $value.containers.volumeMounts }}
            - mountPath: {{ $volume.path}}
              name: {{ $key }}-{{ $index }}
            {{- end }}
      volumes:
      {{- range $index, $volume := $value.containers.volumeMounts }}
        - name: {{ $key }}-{{ $index }}
        {{- if $volume.emptyDir}}
          emptyDir: {{ $volume.emptyDir }}
        {{- end }}
        {{- if $volume.persistentVolumeClaim | default false }}
          persistentVolumeClaim:
            claimName: {{ $key }}-pv-claim
        {{ end }}
      {{ end }}
    {{ end }}
---
{{- end }}