{{- range $key, $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}  
  {{- end }}
spec:
  selector:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}
  {{- end }}
  type: {{ $value.type | default $.Values.global.service.type }}
  ports:
   {{- range $port := $value.ports }}
   {{ $firstValuePort := splitList ":" $port| first | int }}
    - port: {{ $firstValuePort | default $port | int }}
      targetPort: {{ splitList ":" $port| last | int | default $port | int }}
      name: s-{{ $key }}-{{ $firstValuePort | default $port | int }}
      protocol: {{ $.Values.global.service.protocol | default "TCP" }}
{{- end }}
---
{{- end}}
