{{- range $key, $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: fleetman-{{ $key }}
  labels:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}
  {{- end }}
spec:
  selector:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}
  {{- end }}
  type: {{ $value.type | default $.Values.global.service.type }}
  ports:
   {{- range $index,$port := $value.ports }}
   {{- $firstValuePort := splitList ":" $port| first | int }}
    - port: {{ $firstValuePort | default $port | int }}
    {{- if and (eq $value.type "NodePort") (eq $index 0) }}
      nodePort: {{ splitList ":" $port| last | int | default $port | int }}
    {{- end }}
      name: s-{{ $key }}-{{ $firstValuePort | default $port | int }}
{{- end }}
---
{{- end}}
