{{- range $key, $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: fleetman-{{ $key }}
  namespace: {{ $value.namespace | default $.Values.global.namespace }}
  labels:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}
  {{- end }}
spec:
  selector:
  {{- with $value.labels }}
    {{- toYaml . | nindent 4}}
  {{ else }}
    app: {{ $key }}
  {{- end }}
  type: {{ $value.type | default $.Values.global.service.type }}
  ports:
   {{- range $index,$port := $value.ports }}
   {{- $firstValuePort := splitList ":" $port| first | int }}
    - name: s-{{ $key }}-{{ $firstValuePort | default $port | int }}
      port: {{ $firstValuePort | default $port | int }}
      targetPort: {{  splitList ":" $port | last | default $port | int  }}
      protocol: {{$port.protocol | default $.Values.global.service.protocol }}
{{- end }}
---
{{- end}}
